spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymii
    username: postgres
    password: 1Science,3
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true

jwt:
  secret: Hq5Ga/QMogIp8yYaaAM2+xZhp8bnjCu9rQwsD8q4NEnelTS4rpSXDNyd9H5IKpWbthtXpNZv30IoOrk7rM1ztw==
